/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ekemp_practice_ndk_NdkClass */

#ifndef _Included_com_ekemp_practice_ndk_NdkClass
#define _Included_com_ekemp_practice_ndk_NdkClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ekemp_practice_ndk_NdkClass
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ekemp_practice_ndk_NdkClass_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
